from typing import Optional
from pprint import pprint
import firebase_admin
from firebase_admin import credentials, auth


cred = credentials.Certificate("firebase.json")
APP = firebase_admin.initialize_app(cred)


class FirebaseAPI:
    @staticmethod
    def verify_google_token(id_token: str) -> Optional[dict]:
        return auth.verify_id_token(
            id_token=id_token, check_revoked=True
        )


if __name__ == "__main__":
    d = FirebaseAPI.verify_google_token(
        "eyJhbGciOiJSUzI1NiIsImtpZCI6ImE2YzYzNTNmMmEzZWMxMjg2NTA1MzBkMTVmNmM0Y2Y0NTcxYTQ1NTciLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiWWF6YW4gQXJtb3VzaCIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NKMThLbUhSTDY3d2NHNDZLNDhaVF9RN0RVbExyN25rOHhJQ2s1S0VNZExVRW9xPXM5Ni1jIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2NhcmJvbi10cmFjay1zeXN0ZW0iLCJhdWQiOiJjYXJib24tdHJhY2stc3lzdGVtIiwiYXV0aF90aW1lIjoxNzAwMjI5MTE0LCJ1c2VyX2lkIjoiUkZSbmdJVm1Bd1BHY0pxVFVPalZOeFB4SzVzMSIsInN1YiI6IlJGUm5nSVZtQXdQR2NKcVRVT2pWTnhQeEs1czEiLCJpYXQiOjE3MDAyMjkxMTQsImV4cCI6MTcwMDIzMjcxNCwiZW1haWwiOiJ5YXphbi5hcm1vdXNoMUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJnb29nbGUuY29tIjpbIjExNzEyOTg2MDYwMzg2MDUxODQwOCJdLCJlbWFpbCI6WyJ5YXphbi5hcm1vdXNoMUBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJnb29nbGUuY29tIn19.qx9G7SENxVNJG6aVncn4SjmOyyD-loFScBNKl1ndJyAX_n-851D1LC8ctw1ljnhey2TYh9Zp-yFOg0AvL4vkN0XjbzP2qJw7OLB-WPLLKjkjWK3XEGGiXirbCK29dGveQTGXz6UJ8hTMmU26ojnWKfg6ezFqI5SnQYweHP7vtZBbciKgKUSE-pHwZkhBkYCOVtS0aSmGsQpOmxliWRWxuyqkpCqUk_J2pC2p-LHXqthKGIvGvK_akBSjtZvvl-5Db96HMeMr3GF00I4NevOcVs1vkLkCvib9OshlYNPrBtjdsc9loCQe9iRAflQP6Wpm-B_NtW6x0fsTLQs_JyEmNQ"
    )
    pprint(d)
