---
name: Checks

on: [push]

jobs:
  frontend-test:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: utmgdsc/CarbonTrack
      - name: Install packages
        run: |
          cd frontend
          npm install
          npm run lint

  backend-test:
    name: Backend
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: utmgdsc/CarbonTrack
      - name: Install Requirements
        run: |
          cd backend
          pip install -r requirements.txt
          ruff .
