---
name: Checks

on: [push]

jobs:
  frontend-test:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: utmgdsc/CarbonTrack
      - name: Install packages
        run: |
          cd frontend
          npm install
          npm run lint

  backend-test:
    name: Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Requirements
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run linter
        run: |
          cd backend
          ruff .
